# Generated by Django 4.1.5 on 2023-01-19 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("celery_app", "0002_rename_unprocesedcontacts_unprocessedcontacts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contacts", old_name="email", new_name="email_address",
        ),
        migrations.RenameField(
            model_name="unprocessedcontacts",
            old_name="email",
            new_name="email_address",
        ),
    ]
