# Generated by Django 4.1.5 on 2023-01-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celery_app", "0003_rename_email_contacts_email_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacts",
            name="email_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
