# Generated by Django 4.1.5 on 2023-01-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celery_app", "0007_alter_contacts_phone_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="filemetadata", name="file_name",),
        migrations.AlterField(
            model_name="filemetadata",
            name="s3_path",
            field=models.CharField(max_length=255),
        ),
    ]
